/**
 * `useDuplicateStudy` unit tests — Plan 04-05 Task 6.
 *
 * Behavioural contract:
 *   - mutationFn calls `supabase.rpc('duplicate_study', { p_study_id,
 *     p_new_title, p_idempotency_key })`.
 *   - p_idempotency_key is generated by `uuidv7()` per call (UUIDv7
 *     monotonically increasing, matches blocks.ts pattern).
 *   - On success the resolved value is the new study UUID (string).
 *   - On success the ['studies'] query cache is invalidated so the
 *     /studies list refetches.
 *   - On error the rejected promise re-throws (no implicit toast — the
 *     caller wires the user-facing message via mutation's onError).
 *
 * `studies.ts` imports `supabase` (designer-side authenticated client)
 * which reads `import.meta.env.VITE_SUPABASE_*` at construction. We mock
 * `@supabase/supabase-js` before the late-import so the constructor
 * accepts undefined args (no env at test time). This mirrors the pattern
 * used by `responses.test.ts`.
 */
import { describe, expect, it, vi, beforeEach } from 'vitest';
import { renderHook, waitFor } from '@testing-library/react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import type { ReactNode } from 'react';
import { createElement } from 'react';

// Hoisted mock so the late import below sees the stubbed module on first
// resolution. `rpcMock` is the shared spy we observe in each test.
const rpcMock = vi.fn();

vi.mock('@supabase/supabase-js', () => ({
  createClient: () => ({
    auth: {
      getSession: vi.fn().mockResolvedValue({ data: { session: null }, error: null }),
    },
    from: () => ({ select: () => ({}) }),
    rpc: rpcMock,
  }),
}));

// `uuidv7` is the production idempotency-key generator. We stub it to a
// deterministic value so we can assert the RPC call args byte-by-byte.
vi.mock('uuidv7', () => ({
  uuidv7: () => '00000000-0000-7000-8000-000000000001',
}));

const { useDuplicateStudy } = await import('../studies');

function wrapper({ children, qc }: { children: ReactNode; qc: QueryClient }) {
  return createElement(QueryClientProvider, { client: qc }, children);
}

function makeWrapper(qc: QueryClient) {
  return ({ children }: { children: ReactNode }) => wrapper({ children, qc });
}

beforeEach(() => {
  rpcMock.mockReset();
});

describe('useDuplicateStudy', () => {
  it('calls supabase.rpc("duplicate_study", {p_study_id, p_new_title, p_idempotency_key})', async () => {
    rpcMock.mockResolvedValue({
      data: 'new-study-id-abc',
      error: null,
    });

    const qc = new QueryClient({
      defaultOptions: { queries: { retry: false }, mutations: { retry: false } },
    });

    const { result } = renderHook(() => useDuplicateStudy(), {
      wrapper: makeWrapper(qc),
    });

    const newId = await result.current.mutateAsync({ studyId: 'src-1' });

    expect(newId).toBe('new-study-id-abc');
    expect(rpcMock).toHaveBeenCalledTimes(1);
    expect(rpcMock).toHaveBeenCalledWith('duplicate_study', {
      p_study_id: 'src-1',
      p_new_title: null,
      p_idempotency_key: '00000000-0000-7000-8000-000000000001',
    });
  });

  it('passes through newTitle when supplied', async () => {
    rpcMock.mockResolvedValue({ data: 'dup-2', error: null });

    const qc = new QueryClient({
      defaultOptions: { queries: { retry: false }, mutations: { retry: false } },
    });

    const { result } = renderHook(() => useDuplicateStudy(), {
      wrapper: makeWrapper(qc),
    });

    await result.current.mutateAsync({ studyId: 'src-1', newTitle: 'My new copy' });
    expect(rpcMock).toHaveBeenCalledWith('duplicate_study', {
      p_study_id: 'src-1',
      p_new_title: 'My new copy',
      p_idempotency_key: '00000000-0000-7000-8000-000000000001',
    });
  });

  it('invalidates ["studies"] cache on success', async () => {
    rpcMock.mockResolvedValue({ data: 'dup-3', error: null });

    const qc = new QueryClient({
      defaultOptions: { queries: { retry: false }, mutations: { retry: false } },
    });
    const invalidateSpy = vi.spyOn(qc, 'invalidateQueries');

    const { result } = renderHook(() => useDuplicateStudy(), {
      wrapper: makeWrapper(qc),
    });

    await result.current.mutateAsync({ studyId: 'src-1' });

    await waitFor(() => {
      expect(invalidateSpy).toHaveBeenCalledWith({ queryKey: ['studies'] });
    });
  });

  it('re-throws on rpc error', async () => {
    const failure = new Error('forbidden');
    rpcMock.mockResolvedValue({ data: null, error: failure });

    const qc = new QueryClient({
      defaultOptions: { queries: { retry: false }, mutations: { retry: false } },
    });

    const { result } = renderHook(() => useDuplicateStudy(), {
      wrapper: makeWrapper(qc),
    });

    await expect(result.current.mutateAsync({ studyId: 'src-1' })).rejects.toBe(failure);
  });
});
