/**
 * Studies TanStack Query hooks — Plans 01-03 + 01-04.
 *
 * Reads:
 *   - useStudies(workspaceId)           list non-archived studies (UI: /app)
 *   - useStudiesArchived(workspaceId)   archived list (Archived tab on /app)
 *   - useStudy(studyId)                 single study lookup
 *
 * Mutations:
 *   - useCreateStudy(workspaceId)       calls create_study RPC (BUILDER-01)
 *   - useUpdateStudyTitle(studyId)      inline rename (workspace top bar)
 *   - usePublishStudy()                 publish_study RPC (D-27, TESTMGMT-02)
 *   - useMoveStudyToDraft()             move_study_to_draft RPC (TESTMGMT-02)
 *   - useArchiveStudy()                 archive_study RPC (D-28, TESTMGMT-03)
 *   - useRestoreStudy()                 restore_study RPC (D-29, TESTMGMT-03)
 *
 * Toast copy is locked to UI-SPEC.md §"Status lifecycle". Validation errors
 * (the server-side `no_question_blocks` check) surface as a destructive
 * toast with the exact copy-locked message.
 *
 * RPC typing note: the new lifecycle RPCs landed in migration 00004 and the
 * Database type in `types.gen.ts` will be regenerated by the orchestrator
 * post-merge. Until then we call `supabase.rpc(...)` with the RPC name
 * widened via `as never` (mirrors the LooseNavigate pattern from Plan 01-02),
 * structurally validating the returned shape ourselves.
 */

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { toast } from 'sonner';
import { uuidv7 } from 'uuidv7';
import { supabase } from '@/lib/supabase/auth';
import type { Database } from '@/lib/supabase/types.gen';
import { ValidationError } from '@/lib/queries/errors';

export type StudyRow = Database['public']['Tables']['studies']['Row'];

export interface UseStudiesResult {
  studies: StudyRow[];
  isLoading: boolean;
  error: Error | null;
}

function buildStudyQueryKey(workspaceId: string, archived: boolean) {
  return ['studies', workspaceId, archived ? 'archived' : 'active'] as const;
}

/**
 * Cache-invalidation helper for any mutation that changes a study's status
 * or archived_at. We invalidate both the active and archived lists for the
 * owning workspace plus the single-study cache.
 */
function invalidateStudyCaches(
  qc: ReturnType<typeof useQueryClient>,
  workspaceId: string | null | undefined,
  studyId: string,
) {
  if (workspaceId) {
    qc.invalidateQueries({ queryKey: buildStudyQueryKey(workspaceId, false) });
    qc.invalidateQueries({ queryKey: buildStudyQueryKey(workspaceId, true) });
  } else {
    qc.invalidateQueries({ queryKey: ['studies'] });
  }
  qc.invalidateQueries({ queryKey: ['study', studyId] });
}

export function useStudies(workspaceId: string | null | undefined): UseStudiesResult {
  const query = useQuery({
    queryKey: workspaceId ? buildStudyQueryKey(workspaceId, false) : ['studies', 'none', 'active'],
    enabled: !!workspaceId,
    staleTime: 10_000,
    queryFn: async (): Promise<StudyRow[]> => {
      const { data, error } = await supabase
        .from('studies')
        .select('*')
        .eq('workspace_id', workspaceId!)
        .is('archived_at', null)
        .order('updated_at', { ascending: false });
      if (error) throw error;
      return data ?? [];
    },
  });
  return {
    studies: query.data ?? [],
    isLoading: query.isLoading,
    error: (query.error as Error | null) ?? null,
  };
}

/**
 * Archived studies (`archived_at IS NOT NULL`). The Archived tab on /app
 * consumes this; the cache key is independent of the active-studies key so
 * an archive/restore mutation can invalidate both surgically.
 */
export function useStudiesArchived(workspaceId: string | null | undefined): UseStudiesResult {
  const query = useQuery({
    queryKey: workspaceId ? buildStudyQueryKey(workspaceId, true) : ['studies', 'none', 'archived'],
    enabled: !!workspaceId,
    staleTime: 30_000,
    queryFn: async (): Promise<StudyRow[]> => {
      const { data, error } = await supabase
        .from('studies')
        .select('*')
        .eq('workspace_id', workspaceId!)
        .not('archived_at', 'is', null)
        .order('archived_at', { ascending: false });
      if (error) throw error;
      return data ?? [];
    },
  });
  return {
    studies: query.data ?? [],
    isLoading: query.isLoading,
    error: (query.error as Error | null) ?? null,
  };
}

export function useStudy(studyId: string | null | undefined) {
  return useQuery({
    queryKey: ['study', studyId] as const,
    enabled: !!studyId,
    staleTime: 5_000,
    queryFn: async (): Promise<StudyRow | null> => {
      const { data, error } = await supabase
        .from('studies')
        .select('*')
        .eq('id', studyId!)
        .maybeSingle();
      if (error) throw error;
      return data;
    },
  });
}

export interface CreateStudyResult {
  studyId: string;
}

/**
 * BUILDER-01: creates a draft study + welcome + thanks atomically.
 *
 * The RPC `create_study(ws_id, study_title)` is SECURITY DEFINER and inserts
 * both pinned blocks in one transaction, returning the new study id. On
 * success we invalidate the active-studies cache so the list refreshes.
 */
export function useCreateStudy(workspaceId: string | null | undefined) {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async (input: { title?: string } = {}): Promise<CreateStudyResult> => {
      if (!workspaceId) throw new Error('Workspace not loaded');
      const { data, error } = await supabase.rpc('create_study', {
        ws_id: workspaceId,
        study_title: input.title ?? 'Untitled test',
      });
      if (error) throw error;
      if (!data) throw new Error('create_study returned no id');
      return { studyId: data };
    },
    onSuccess: () => {
      if (workspaceId) {
        qc.invalidateQueries({ queryKey: buildStudyQueryKey(workspaceId, false) });
      }
    },
  });
}

/**
 * Inline-editable test name — `<WorkspaceTopBar>` consumes this via blur/Enter.
 *
 * Optimistic update: we pre-populate `['study', studyId]` with the new title
 * before the network round-trip; if the server returns a different shape
 * (RLS strip, etc.) we reconcile from the response payload.
 */
export function useUpdateStudyTitle(studyId: string | null | undefined) {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async (input: { title: string }) => {
      if (!studyId) throw new Error('Study not loaded');
      const { data, error } = await supabase
        .from('studies')
        .update({ title: input.title })
        .eq('id', studyId)
        .select()
        .maybeSingle();
      if (error) throw error;
      return data;
    },
    onMutate: async (input) => {
      if (!studyId) return;
      await qc.cancelQueries({ queryKey: ['study', studyId] });
      const previous = qc.getQueryData<StudyRow | null>(['study', studyId]);
      if (previous) {
        qc.setQueryData<StudyRow>(['study', studyId], {
          ...previous,
          title: input.title,
        });
      }
      return { previous };
    },
    onError: (_err, _input, ctx) => {
      if (ctx?.previous) {
        qc.setQueryData(['study', studyId], ctx.previous);
      }
    },
    onSuccess: (data) => {
      if (data) {
        qc.setQueryData(['study', studyId], data);
        qc.invalidateQueries({
          queryKey: ['studies', data.workspace_id, 'active'],
        });
      }
    },
  });
}

// ===========================================================================
// Plan 01-04: status lifecycle mutations (D-27 / D-28 / D-29)
// ===========================================================================

/**
 * Server-side error code matcher. The publish RPC raises a Postgres
 * exception whose `message` carries the literal code we want to surface
 * (`no_question_blocks`, `forbidden`, `study_not_found`). PostgREST forwards
 * the message text into `PostgrestError.message`; we string-match defensively
 * because the precise wire format may include a "ERROR: " prefix or trailing
 * SQLSTATE on some Supabase versions.
 */
function hasErrorCode(err: unknown, code: string): boolean {
  if (!err || typeof err !== 'object') return false;
  const msg = (err as { message?: string }).message;
  return typeof msg === 'string' && msg.includes(code);
}

export interface PublishStudyResult {
  run_token: string;
  status: 'published';
}

/**
 * D-27 publish flow.
 *
 * On success:
 *   - Copies `${origin}/r/{run_token}` to clipboard (best-effort — clipboard
 *     may be denied by browser permissions; the toast still fires).
 *   - Toasts "Test published. Share link copied to clipboard." (UI-SPEC.md
 *     §Status lifecycle copy lock).
 *   - Invalidates list + single-study caches.
 *
 * On `no_question_blocks` server error: throws `ValidationError` so the
 * caller's `onError` can surface the destructive toast "Add at least one
 * question block before publishing." (copy lock).
 */
export function usePublishStudy() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async (input: {
      studyId: string;
      workspaceId?: string | null;
    }): Promise<PublishStudyResult> => {
      // `publish_study` was added in migration 00004 and is not yet in
      // types.gen.ts — narrowed via `as never` (regenerated post-merge).
      const { data, error } = await supabase.rpc(
        'publish_study' as never,
        { study_uuid: input.studyId } as never,
      );
      if (error) {
        if (hasErrorCode(error, 'no_question_blocks')) {
          throw new ValidationError('NO_QUESTION_BLOCKS');
        }
        throw error;
      }
      // publish_study returns TABLE(run_token text, status text); supabase
      // gives us either an array of rows or a single row depending on the
      // PostgREST client version. Normalise to the first row.
      const row = Array.isArray(data) ? data[0] : data;
      if (!row || typeof row !== 'object') {
        throw new Error('publish_study returned no payload');
      }
      const payload = row as { run_token?: unknown; status?: unknown };
      if (typeof payload.run_token !== 'string') {
        throw new Error('publish_study returned no run_token');
      }
      return {
        run_token: payload.run_token,
        status: 'published',
      };
    },
    onSuccess: async (data, input) => {
      // Best-effort clipboard copy. Failure is silent — the toast and the
      // dialog still surface the URL so the user has a copy path.
      try {
        const url = `${window.location.origin}/r/${data.run_token}`;
        await navigator.clipboard.writeText(url);
      } catch {
        /* clipboard may be denied; toast + dialog still show the link */
      }
      toast.success('Test published. Share link copied to clipboard.');
      invalidateStudyCaches(qc, input.workspaceId, input.studyId);
    },
    onError: (err) => {
      if (err instanceof ValidationError && err.code === 'NO_QUESTION_BLOCKS') {
        toast.error('Add at least one question block before publishing.');
        return;
      }
      toast.error("Couldn't publish. Try again in a moment.");
    },
  });
}

/**
 * TESTMGMT-02 "Move to draft" — published → draft. Run-token preserved (D-19).
 */
export function useMoveStudyToDraft() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async (input: { studyId: string; workspaceId?: string | null }): Promise<void> => {
      const { error } = await supabase.rpc(
        'move_study_to_draft' as never,
        { study_uuid: input.studyId } as never,
      );
      if (error) throw error;
    },
    onSuccess: (_data, input) => {
      toast.success("Moved to draft. The link won't accept new responses until you publish again.");
      invalidateStudyCaches(qc, input.workspaceId, input.studyId);
    },
    onError: () => {
      toast.error("Couldn't move to draft. Try again in a moment.");
    },
  });
}

/**
 * D-28 archive (any → archived). UI-layer confirm dialog precedes this call.
 */
export function useArchiveStudy() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async (input: { studyId: string; workspaceId?: string | null }): Promise<void> => {
      const { error } = await supabase.rpc(
        'archive_study' as never,
        { study_uuid: input.studyId } as never,
      );
      if (error) throw error;
    },
    onSuccess: (_data, input) => {
      toast.success('Test archived.');
      invalidateStudyCaches(qc, input.workspaceId, input.studyId);
    },
    onError: () => {
      toast.error("Couldn't archive. Try again in a moment.");
    },
  });
}

// ===========================================================================
// Plan 04-05 Task 6: duplicate_study mutation hook (TESTMGMT-04)
// ===========================================================================

/**
 * `useDuplicateStudy` — calls migration 00017's `duplicate_study` RPC.
 *
 * Designer clicks «Дублировать» in /studies row hover-menu (Task 7) OR in the
 * builder topbar kebab (Task 7). Either entry point invokes the same hook:
 *
 *   const dup = useDuplicateStudy();
 *   const newId = await dup.mutateAsync({ studyId, newTitle? });
 *   navigate({ to: '/studies/$id/edit', params: { id: newId } });
 *
 * Idempotency key generated locally via `uuidv7()` — same pattern as
 * blocks.ts' insert/update/duplicate mutations. Rapid double-clicks on the
 * action menu produce ONE duplicate at the server level (00017 audit table
 * dedupes via UNIQUE(study_id, idempotency_key)) AND the disabled-state on
 * the menu item prevents the second click at the UI level.
 *
 * On success: invalidate `['studies']` so the home list refetches the new
 * copy. The list is partitioned by workspace_id internally but the
 * invalidation is by top-level key so all workspace partitions refresh.
 *
 * On error: rethrow. The caller wires `mutation.onError` to surface a
 * toast / alert (Task 7).
 *
 * RPC return type: the migration 00017 signature is
 *   `duplicate_study(p_study_id uuid, p_new_title text, p_idempotency_key uuid) RETURNS uuid`
 * — when called via `.rpc(...)`, supabase-js gives us `data: string | null`.
 * We cast through `as never` because the regenerated types.gen.ts won't
 * include 00017's RPC until the orchestrator runs `gen-types` post-merge
 * (mirrors the pattern Phase 1 publish/archive RPCs use).
 */
export function useDuplicateStudy() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async (input: { studyId: string; newTitle?: string }): Promise<string> => {
      const { data, error } = await supabase.rpc(
        'duplicate_study' as never,
        {
          p_study_id: input.studyId,
          p_new_title: input.newTitle ?? null,
          p_idempotency_key: uuidv7(),
        } as never,
      );
      if (error) throw error;
      // `data` is typed `never` until types.gen.ts is regenerated post-merge;
      // narrow via runtime structural check.
      const id = data as unknown;
      if (typeof id !== 'string' || id.length === 0) {
        throw new Error('duplicate_study returned no id');
      }
      return id;
    },
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ['studies'] });
    },
  });
}

/**
 * D-29 restore (archived → draft). Run-token preserved per D-19.
 */
export function useRestoreStudy() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async (input: { studyId: string; workspaceId?: string | null }): Promise<void> => {
      const { error } = await supabase.rpc(
        'restore_study' as never,
        { study_uuid: input.studyId } as never,
      );
      if (error) throw error;
    },
    onSuccess: (_data, input) => {
      toast.success('Restored to draft.');
      invalidateStudyCaches(qc, input.workspaceId, input.studyId);
    },
    onError: () => {
      toast.error("Couldn't restore. Try again in a moment.");
    },
  });
}
